### ISSUE TITLE
 SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first

### ISSUE THREAD

**Issue by jonj27** [chandrabezzo/flutter_meta_sdk#3]
I have followed the steps for the configuration for Android (not looked at iOS yet). 

When hitting firing up my local emulator i see the following:

`E/GeneratedPluginRegistrant( 4481): Error registering plugin flutter_meta_sdk, com.solusibejo.flutter_meta_sdk.FlutterMetaSdkPlugin
E/GeneratedPluginRegistrant( 4481): The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/GeneratedPluginRegistrant( 4481): 	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
E/GeneratedPluginRegistrant( 4481): 	at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.kt:642)
E/GeneratedPluginRegistrant( 4481): 	at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.kt:82)
E/GeneratedPluginRegistrant( 4481): 	at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.kt:118)
E/GeneratedPluginRegistrant( 4481): 	at com.facebook.appevents.AppEventsLogger.<init>(Unknown Source:0)
E/GeneratedPluginRegistrant( 4481): 	at com.facebook.appevents.AppEventsLogger$Companion.newLogger(AppEventsLogger.kt:369)
E/GeneratedPluginRegistrant( 4481): 	at com.solusibejo.flutter_meta_sdk.FlutterMetaSdkPlugin.onAttachedToEngine(FlutterMetaSdkPlugin.kt:30)
E/GeneratedPluginRegistrant( 4481): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:146)
E/GeneratedPluginRegistrant( 4481): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:74)
E/GeneratedPluginRegistrant( 4481): 	at java.lang.reflect.Method.invoke(Native Method)`

Any suggestions gratefully received.

**Comment by jonj27** [comment]
I also notice this further up the stack too.

`E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): Failed to handle method call
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at com.solusibejo.flutter_meta_sdk.FlutterMetaSdkPlugin.onMethodCall(FlutterMetaSdkPlugin.kt:49)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/MethodChannel#solusibejo.com/flutter_meta_sdk(21781): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
D/TrafficStats(21781): tagSocket(149) with statsTag=0xffffffff, statsUid=-1`

**Comment by vagrantrobbie** [comment]
Is this still open? Did you make sure you had added the `<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>` and  `<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>` as an immediate child of the application tag?

**Comment by burakJs** [comment]
I have same issue. Any update ?
